services:
  recon:
    build:
      context: ..       # Points to pentest_agent root directory
      dockerfile: docker/recon.Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    container_name: recon
    environment:
      - PDCP_API_KEY
      - GITHUB_KEY
      - INDEX_STORAGE_DIR
      - OPENAI_API_KEY
      - http_proxy
      - https_proxy
    volumes:
      - ..:/app
  planning:
    build:
      context: ..        # Points to pentest_agent root directory
      dockerfile: docker/planning.Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    container_name: planning
    environment:
      - PDCP_API_KEY
      - GITHUB_KEY
      - INDEX_STORAGE_DIR
      - OPENAI_API_KEY
      - DEEPSEEK_API_KEY
      - GITLAB_TOKEN
      - http_proxy
      - https_proxy
    volumes:
      - ..:/app
  execution:
    build:
      context: ..        # Points to pentest_agent root directory
      dockerfile: docker/execution.Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    container_name: execution
    environment:
      - PDCP_API_KEY
      - GITHUB_KEY
      - INDEX_STORAGE_DIR
      - OPENAI_API_KEY
      - http_proxy
      - https_proxy
    volumes:
      - ..:/app
